export default {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#a5d390",
        "primary": "#00465c",
        "inverse-surface": "#313030",
        "error": "#ba1a1a",
        "tertiary-container": "#3a622b",
        "on-surface": "#1c1b1c",
        "tertiary": "#234a15",
        "on-tertiary": "#ffffff",
        "surface-bright": "#fcf9f8",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#004d64",
        "on-secondary": "#ffffff",
        "primary-container": "#125f79",
        "on-primary-fixed": "#001f2a",
        "surface-variant": "#e5e2e1",
        "inverse-on-surface": "#f3f0f0",
        "on-tertiary-fixed": "#042100",
        "surface": "#fcf9f8",
        "surface-tint": "#1d6680",
        "on-secondary-container": "#006d7c",
        "outline": "#70787d",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#81d3e4",
        "surface-container-low": "#f6f3f2",
        "on-tertiary-fixed-variant": "#29501b",
        "on-surface-variant": "#40484c",
        "inverse-primary": "#8fcfed",
        "on-primary-container": "#97d7f5",
        "background": "#fcf9f8",
        "secondary-container": "#9aecfe",
        "tertiary-fixed": "#c0f0a9",
        "secondary-fixed": "#a2eeff",
        "primary-fixed-dim": "#8fcfed",
        "primary-fixed": "#bde9ff",
        "surface-container-high": "#ebe7e7",
        "surface-container-highest": "#e5e2e1",
        "secondary": "#006877",
        "surface-container": "#f0eded",
        "on-secondary-fixed-variant": "#004e5a",
        "outline-variant": "#bfc8cd",
        "on-secondary-fixed": "#001f25",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1c1b1c",
        "surface-dim": "#dcd9d9",
        "on-tertiary-container": "#addc97"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "gutter": "1.5rem",
        "gutter-mobile": "1rem",
        "margin": "2.5rem",
        "margin-mobile": "1rem"
      },
      fontFamily: {
        "label-caps": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-xl": ["Plus Jakarta Sans"],
        "headline-xl-mobile": ["Plus Jakarta Sans"],
        "display-hero": ["Plus Jakarta Sans"],
        "display-hero-mobile": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-xl-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-hero": ["44px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-hero-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }]
      }
    }
  }
}