export const AUDITORIA = {
  borrador: true,
  expediente: 'AUD-2026-Q4-089',
  marco: 'ISO 56002:2019',
  estado: 'En revisión formal',
  avance: 92,
  revisor: { nombre: 'Carlos Mendoza', iniciales: 'CM', rol: 'Consultor revisor · Trust 4P' },
  auditado: { nombre: 'Alejandro Morales', iniciales: 'AM', rol: 'Representante · InnovaTech Logistics Corp.' },
  indicadores: {
    requisitosPresentados: 16,
    requisitosTotales: 16,
    conformes: 14,
    conObservacion: 2,
    indiceConformidad: 94.2,
    variacion: 4.8,
    algoritmoIntegridad: 'SHA-256',
    proximaRevision: '15 de noviembre de 2026',
  },
  pilares: [
    { id: 'proposito', codigo: 'P1', nombre: 'Propósito y gobernanza', clausulas: 'ISO 5.1 Liderazgo · ISO 5.2 Política de innovación', aprobadas: 4, total: 4, estado: 'conforme' },
    { id: 'procesos', codigo: 'P2', nombre: 'Procesos y embudos', clausulas: 'ISO 8.1 Planificación operativa · ISO 8.3 Iniciativas', aprobadas: 3, total: 4, estado: 'observacion' },
    { id: 'personas', codigo: 'P3', nombre: 'Personas y cultura', clausulas: 'ISO 7.2 Competencia · ISO 7.3 Concienciación', aprobadas: 4, total: 4, estado: 'conforme' },
    { id: 'plataforma', codigo: 'P4', nombre: 'Plataforma y herramientas', clausulas: 'ISO 7.1 Recursos · ISO 7.5 Información documentada', aprobadas: 3, total: 4, estado: 'noConforme' },
  ],
  hallazgos: [
    {
      id: 'NC-01',
      tipo: 'noConforme',
      titulo: 'No conformidad menor · Plataforma',
      descripcion:
        'Falta una bitácora unificada de clasificación de hipótesis en los repositorios dispersos. Requiere vincular la trazabilidad con la iniciativa de plataforma.',
      clausula: 'Cláusula ISO 7.1.3 y 7.5',
      plazo: 'Plazo: 15 días',
      accion: 'Ver evidencia asignada',
    },
    {
      id: 'OBS-02',
      tipo: 'observacion',
      titulo: 'Observación · Procesos',
      descripcion:
        'Formalizar en acta el umbral cuantitativo de descarte de hipótesis para asegurar la trazabilidad antes del punto de decisión.',
      clausula: 'Cláusula ISO 8.3 y 9.1',
      plazo: 'Oportunidad de mejora',
      accion: 'Registrar nota técnica',
    },
  ],
  evidencias: [
    {
      id: 'EV-01',
      archivo: 'Politica_asignacion_presupuesto_2025.pdf',
      formato: 'pdf',
      tamano: '1.8 MB',
      pilarId: 'procesos',
      clausula: 'ISO 8.3.2 Asignación de recursos',
      estado: 'conforme',
      etiquetaEstado: 'Aprobada',
      subidoPor: 'Alejandro Morales',
      fecha: '24 Oct 2026',
      hash: '7f8c…3a19',
      nota: null,
    },
    {
      id: 'EV-02',
      archivo: 'Acta_directorio_tesis_innovacion.pdf',
      formato: 'pdf',
      tamano: '3.4 MB',
      pilarId: 'proposito',
      clausula: 'ISO 5.1 Compromiso de la dirección',
      estado: 'conforme',
      etiquetaEstado: 'Aprobada',
      subidoPor: 'Alejandro Morales',
      fecha: '22 Oct 2026',
      hash: '4b12…9e88',
      nota: null,
    },
    {
      id: 'EV-03',
      archivo: 'Matriz_competencias_innovacion_2026.xlsx',
      formato: 'hoja',
      tamano: '890 KB',
      pilarId: 'personas',
      clausula: 'ISO 7.2 Competencia del personal',
      estado: 'conforme',
      etiquetaEstado: 'Aprobada',
      subidoPor: 'Alejandro Morales',
      fecha: '21 Oct 2026',
      hash: '2c99…df41',
      nota: null,
    },
    {
      id: 'EV-04',
      archivo: 'Inventario_arquitectura_experimentacion.docx',
      formato: 'texto',
      tamano: '2.1 MB',
      pilarId: 'plataforma',
      clausula: 'ISO 7.1.3 Infraestructura',
      estado: 'observada',
      etiquetaEstado: 'Observada · en subsanación',
      subidoPor: 'Alejandro Morales',
      fecha: '20 Oct 2026',
      hash: 'a10f…77c3',
      nota: 'Falta anexar el protocolo de conexión al repositorio central y los accesos de consulta del registro de eventos.',
      vence: '08 Nov 2026',
    },
    {
      id: 'EV-05',
      archivo: 'Bitacora_descarte_hipotesis_Q3.pdf',
      formato: 'pdf',
      tamano: '1.2 MB',
      pilarId: 'procesos',
      clausula: 'ISO 9.1 Seguimiento y medición',
      estado: 'conforme',
      etiquetaEstado: 'Aprobada',
      subidoPor: 'Alejandro Morales',
      fecha: '19 Oct 2026',
      hash: '99a1…11df',
      nota: null,
    },
  ],
  dictamen: {
    numero: 'TR4P-REV-2026-N3',
    titulo: 'Nivel 3 (Sistemático) ratificado en revisión interna',
    texto:
      'La organización satisface el 94,2 % de los criterios evaluados en esta revisión interna frente a la norma ISO 56002:2019. Queda habilitada para iniciar el plan de mejora hacia el nivel 4.',
    vigencia: '24 meses',
    hash: 'e3b0c44298fc1c14',
  },
}
