export const TIPOS_EVENTO = [
  { id: 'acceso', nombre: 'Acceso', icono: 'login', descripcion: 'Inicios de sesión y cambios de credenciales' },
  { id: 'diagnostico', nombre: 'Diagnóstico', icono: 'assignment', descripcion: 'Respuestas y cierre de diagnósticos' },
  { id: 'calculo', nombre: 'Cálculo', icono: 'calculate', descripcion: 'Ejecuciones del motor de cálculo del índice' },
  { id: 'agente', nombre: 'Agente', icono: 'smart_toy', descripcion: 'Ejecuciones del servicio de evaluación asistida' },
  { id: 'modelo', nombre: 'Modelo', icono: 'tune', descripcion: 'Cambios en dimensiones, preguntas y rúbrica' },
]

export const BITACORA_AUDITORIA = {
  borrador: true,
  empresaNombre: 'InnovaTech Logistics Corp.',
  empresaId: 'EMP-INNOVATECH-01',
  diagnosticoId: 'DIAG-2026-8842',
  modeloVersion: '0.1-borrador',
  eventos: [
    {
      id: 'EVT-0091',
      marca: '2026-10-24 14:38:02',
      tipo: 'agente',
      actor: 'servicio-agente',
      rol: 'Sistema',
      resumen: 'Evaluación asistida completada para el diagnóstico',
      resultado: 'conforme',
      hash: '7f8c4a19b2d0e5f3',
      detalle: {
        'Versión del modelo': '0.1-borrador',
        'Modelo de lenguaje': 'Qwen3-Next-80B',
        'Fragmentos recuperados': '6 de la base de conocimiento',
        'Validación de esquema': 'Correcta',
        'Duración': '11.4 s',
        'Reintentos': '0',
      },
    },
    {
      id: 'EVT-0090',
      marca: '2026-10-24 14:37:48',
      tipo: 'agente',
      actor: 'servicio-agente',
      rol: 'Sistema',
      resumen: 'Respuesta del agente rechazada por esquema inválido',
      resultado: 'rechazado',
      hash: '4b129e88c7a01d54',
      detalle: {
        'Versión del modelo': '0.1-borrador',
        'Modelo de lenguaje': 'Qwen3-Next-80B',
        'Motivo del rechazo': 'Campo puntajePorDimension ausente',
        'Validación de esquema': 'Fallida',
        'Acción tomada': 'Reintento con la misma petición',
        'Duración': '9.8 s',
      },
    },
    {
      id: 'EVT-0089',
      marca: '2026-10-24 14:36:15',
      tipo: 'calculo',
      actor: 'motor-calculo',
      rol: 'Sistema',
      resumen: 'Índice de madurez calculado: 74 puntos, nivel 3',
      resultado: 'conforme',
      hash: '2c99df41a3b85602',
      detalle: {
        'Versión del modelo': '0.1-borrador',
        'Preguntas consideradas': '16 de 16',
        'Índice global': '74',
        'Nivel asignado': '3 — Sistemático',
        'Reproducible': 'Sí, misma entrada produce el mismo resultado',
      },
    },
    {
      id: 'EVT-0088',
      marca: '2026-10-24 14:35:50',
      tipo: 'diagnostico',
      actor: 'Alejandro Morales',
      rol: 'Representante de empresa',
      resumen: 'Diagnóstico cerrado y enviado a evaluación',
      resultado: 'conforme',
      hash: '99a111dfe4c73028',
      detalle: {
        'Diagnóstico': 'DIAG-2026-8842',
        'Preguntas respondidas': '16 de 16',
        'Tiempo total': '38 minutos',
        'Versión del modelo aplicada': '0.1-borrador',
      },
    },
    {
      id: 'EVT-0087',
      marca: '2026-10-24 13:58:11',
      tipo: 'diagnostico',
      actor: 'Alejandro Morales',
      rol: 'Representante de empresa',
      resumen: 'Avance guardado automáticamente: 12 de 16 preguntas',
      resultado: 'conforme',
      hash: 'e3b0c44298fc1c14',
      detalle: {
        'Diagnóstico': 'DIAG-2026-8842',
        'Preguntas respondidas': '12 de 16',
        'Dimensión en curso': 'Personas',
      },
    },
    {
      id: 'EVT-0086',
      marca: '2026-10-24 13:20:44',
      tipo: 'acceso',
      actor: 'Alejandro Morales',
      rol: 'Representante de empresa',
      resumen: 'Inicio de sesión correcto',
      resultado: 'conforme',
      hash: '1a2b3c4d5e6f7081',
      detalle: {
        'Resultado': 'Sesión creada',
        'Intentos fallidos previos': '0',
      },
    },
    {
      id: 'EVT-0085',
      marca: '2026-10-23 09:12:03',
      tipo: 'modelo',
      actor: 'Administrador',
      rol: 'Administrador',
      resumen: 'Ponderación de dimensiones actualizada',
      resultado: 'atencion',
      hash: '8d7e6f5a4b3c2d10',
      detalle: {
        'Cambio': 'Pesos de las cuatro dimensiones fijados en 25%',
        'Versión resultante': '0.1-borrador',
        'Diagnósticos afectados': 'Ninguno, los cerrados conservan su versión',
      },
    },
    {
      id: 'EVT-0084',
      marca: '2026-10-22 16:45:30',
      tipo: 'acceso',
      actor: 'desconocido',
      rol: 'No autenticado',
      resumen: 'Cuenta bloqueada temporalmente tras cinco intentos fallidos',
      resultado: 'atencion',
      hash: '5f4e3d2c1b0a9988',
      detalle: {
        'Intentos fallidos': '5 consecutivos',
        'Acción': 'Bloqueo temporal de 15 minutos',
        'Nota': 'El sistema no revela si el correo existe',
      },
    },
  ],
}
