export const EVOLUCION_HISTORICA = {
  borrador: true,
  diagnosticoId: 'DIAG-2026-8842',
  empresaNombre: 'InnovaTech Logistics Corp.',
  responsable: 'Alejandro Morales',
  iniciales: 'AM',
  dimensiones: [
    { id: 'proposito', numero: 1, nombre: 'Propósito', subtitulo: 'Tesis, asignación de capital y comités' },
    { id: 'procesos', numero: 2, nombre: 'Procesos', subtitulo: 'Etapas, validación y cadencia' },
    { id: 'personas', numero: 3, nombre: 'Personas', subtitulo: 'Competencias, incentivos y tolerancia al error' },
    { id: 'plataforma', numero: 4, nombre: 'Plataforma', subtitulo: 'Tecnología, trazabilidad y métricas' },
  ],
  periodos: [
    {
      anio: '2024',
      etiqueta: 'Línea base',
      proyectado: false,
      indice: 48,
      puntajes: { proposito: 60, procesos: 50, personas: 45, plataforma: 38 },
      hito: 'Formalización de la primera tesis de innovación y creación del comité de operaciones.',
    },
    {
      anio: '2025',
      etiqueta: 'Consolidación',
      proyectado: false,
      indice: 61,
      puntajes: { proposito: 72, procesos: 64, personas: 58, plataforma: 50 },
      hito: 'Implantación de objetivos trimestrales y migración hacia fondos escalonados.',
    },
    {
      anio: '2026',
      etiqueta: 'Diagnóstico actual',
      proyectado: false,
      indice: 74,
      puntajes: { proposito: 88, procesos: 75, personas: 70, plataforma: 63 },
      hito: 'Diagnóstico completo y detección de contradicciones entre velocidad de entrega y rigor de control.',
    },
    {
      anio: '2027',
      etiqueta: 'Meta',
      proyectado: true,
      indice: 86,
      puntajes: { proposito: 94, procesos: 87, personas: 84, plataforma: 81 },
      hito: 'Repositorio central de experimentación, fondeo continuo y formación en resolución sistemática.',
    },
  ],
  niveles: [
    { numero: 1, nombre: 'Inicial', desde: 0, hasta: 25 },
    { numero: 2, nombre: 'En desarrollo', desde: 26, hasta: 50 },
    { numero: 3, nombre: 'Sistemático', desde: 51, hasta: 75 },
    { numero: 4, nombre: 'Optimizado', desde: 76, hasta: 100 },
  ],
  iniciativasPorDimension: {
    proposito: 'Comité con potestad presupuestaria delegada',
    procesos: 'Fondeo continuo por hitos verificables',
    personas: 'Marco de incentivos al aprendizaje validado',
    plataforma: 'Repositorio central de experimentación',
  },
}
