export const PLAN_ESTRATEGICO = {
  borrador: true,
  diagnosticoId: 'DIAG-2026-8842',
  empresaNombre: 'InnovaTech Logistics Corp.',
  empresaNit: '900.842.119-4',
  responsable: 'Alejandro Morales',
  ciclo: '2026-Q1',
  indiceActual: 74,
  meta: 86,
  nivelMeta: 4,
  dimensiones: [
    {
      id: 'proposito',
      numero: 1,
      nombre: 'Propósito',
      puntaje: 88,
      nivel: 4,
      etiquetaEstado: 'Fortaleza',
      estado: 'Tesis de innovación sólida y gobernanza activa de portafolio.',
      siguientePaso: 'Autonomía delegada en comités de micro-fondos.',
      severidad: 'bien',
    },
    {
      id: 'procesos',
      numero: 2,
      nombre: 'Procesos',
      puntaje: 75,
      nivel: 3,
      etiquetaEstado: 'Estado',
      estado: 'Presupuestos ágiles trimestrales operativos pero rígidos para pivotar rápido.',
      siguientePaso: 'Migrar a fondeo dinámico y continuo por hitos.',
      severidad: 'medio',
    },
    {
      id: 'personas',
      numero: 3,
      nombre: 'Personas',
      puntaje: 70,
      nivel: 3,
      etiquetaEstado: 'Estado',
      estado: 'Intraemprendimiento funcional pero dependiente de líderes específicos.',
      siguientePaso: 'Incentivos que reconozcan el descarte temprano de hipótesis.',
      severidad: 'medio',
    },
    {
      id: 'plataforma',
      numero: 4,
      nombre: 'Plataforma',
      puntaje: 63,
      nivel: 2,
      etiquetaEstado: 'Diagnóstico',
      estado: 'Herramientas desconectadas, dispersión de datos y baja asistencia automatizada.',
      siguientePaso: 'Unificación en un repositorio central.',
      severidad: 'critico',
    },
  ],
  contradicciones: [
    {
      id: 'CON-01',
      referencia: 'Parámetro 9 vs 35',
      entre: 'Velocidad de experimentación',
      contra: 'Control presupuestario',
      solucion:
        'Principio de acción periódica a continua: fondos por micro-ciclos desbloqueados por evidencia.',
    },
    {
      id: 'CON-02',
      referencia: 'Parámetro 2 vs 27',
      entre: 'Innovación descentralizada',
      contra: 'Gobernanza y seguridad',
      solucion:
        'Principios de segmentación y mediación: clasificación asistida con revisión humana sobre los casos dudosos.',
    },
  ],
  iniciativas: [
    {
      id: 'INI-01',
      dimensionId: 'plataforma',
      titulo: 'Repositorio central de experimentación',
      descripcion:
        'Consolidar las herramientas dispersas en una arquitectura unificada, con clasificación asistida de hipótesis y detección de experimentos duplicados.',
      principio: 'Segmentación y mediación',
      semanas: 6,
      impactoDimension: 8.5,
      impactoGlobal: 2.1,
      opcional: false,
      focoCritico: true,
    },
    {
      id: 'INI-02',
      dimensionId: 'personas',
      titulo: 'Marco de incentivos al aprendizaje validado',
      descripcion:
        'Formalizar reconocimientos por el descarte temprano de hipótesis inviables, antes del punto de decisión presupuestaria.',
      principio: 'Acción previa',
      semanas: 4,
      impactoDimension: 5.0,
      impactoGlobal: 1.2,
      opcional: false,
      focoCritico: false,
    },
    {
      id: 'INI-03',
      dimensionId: 'procesos',
      titulo: 'Fondeo continuo por hitos verificables',
      descripcion:
        'Transitar de aprobaciones presupuestarias trimestrales estáticas a fondos continuos gobernados por hitos con evidencia de tracción.',
      principio: 'Acción periódica a continua',
      semanas: 8,
      impactoDimension: 6.0,
      impactoGlobal: 1.5,
      opcional: false,
      focoCritico: false,
    },
    {
      id: 'INI-04',
      dimensionId: 'personas',
      titulo: 'Formación en resolución sistemática de problemas',
      descripcion:
        'Programa de formación en TRIZ y Design Thinking dirigido a líderes de área y equipos funcionales.',
      principio: 'Autoservicio y capacitación cruzada',
      semanas: 5,
      impactoDimension: 3.5,
      impactoGlobal: 0.8,
      opcional: true,
      focoCritico: false,
    },
  ],
}
